### ISSUE TITLE
Error during system update Error: unexpected-error

### ISSUE THREAD

**Issue by lsd05** [stringbean/homebridge-drayton-wiser#11]
Suddenly getting this error constantly pop up and have no idea why. Any help much appreciated 

Error during system update Error: unexpected-error
    at WiserClient.request (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:340:13)
    at WiserClient.fullStatus (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:68:22)
    at WiserPlatformPlugin.updateSystem (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/src/WiserPlatformPlugin.ts:101:26)

Thanks

**Comment by tcsoft** [comment]
Getting this too.

**Comment by mar894q** [comment]
I also get this. Did anyone find a solution?
