### ISSUE TITLE
[drayton-wiser] Error during system update Error:

### ISSUE THREAD

**Issue by MingChops** [stringbean/homebridge-drayton-wiser#5]
I have an issue with the plugin showing the following information on the Homebridge status page log:

[12/5/2020, 5:07:32 PM] [drayton-wiser] Error during system update Error: system-not-found
    at WiserClient.request (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:337:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at WiserClient.fullStatus (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:68:22)
    at WiserPlatformPlugin.updateSystem (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/src/WiserPlatformPlugin.ts:101:26)

I have no idea why or what it means? It is quite random in it's appearance in the log. The plugin otherwise seems to work fine.

**Comment by thelewiss1** [comment]
Similar errors also. I think it's stopping the service also though.
https://gist.github.com/thelewiss1/d3de90e5b4064c98e76e14cd63fcff06

**Comment by LewisSpring** [comment]
Update: It seems to affect my recently added TRV: It often says No Response but also somehow changes the temperature.

**Comment by DACOOX360X** [comment]
I have exactly the same issue!

The plugin was working seamlessly with HomeKit and Wiser Heat for 3 months. Then added another Wiser TRV to the system and now HomeKit struggles to get the set-point temperature updates (which should follow the Wiser Heat schedule).

Current room temperatures seem to be unaffected and correct.

Speculation:
Maybe because the system is constantly polling the current temp, and only issues a set point temp change when the change happens, which Homebridge misses and runs on the old set-point figure. This is just speculation. 

See attached screen dump of the errors I now get in the Homebridge terminal log.
![IMG_0055](https://user-images.githubusercontent.com/78427112/106613282-ec8f9d00-6561-11eb-86a2-510d8ab5225b.png)

**Comment by LewisSpring** [comment]
@MingChops @DACOOX360X 
Do either of you have the homebridge-tuya-web plug-in? I found that Drayton-Wiser became much more responsive and worked better _**when i removed it. [edit (words missing my bad)]**_

I still get these errors - and a `FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory` a couple hours ago I did not notice (that might be to do with homebridge-tuya though)

**Comment by DACOOX360X** [comment]
> @MingChops @DACOOX360X
> Do either of you have the homebridge-tuya-web plug-in? I found that Drayton-Wiser became much more responsive and worked better.
> 
> I still get these errors - and a `FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory` a couple hours ago I did not notice (that might be to do with homebridge-tuya though)

Thanks for the super fast reply 😀👍

No I haven’t heard of homebridge-tuya-web until now.
I will give it a go and will report back!

Reckon the homebridge-tuya-web plugin helps largely because it polls every 10 seconds?

Can you do us one more favour and share the homebridge-tuya-web settings you use in your setup?

Thanks so much!

**Comment by LewisSpring** [comment]
@DACOOX360X
Just realised my wording: I meant if you have it- disable it. It's for certain wi-fi smart devices

**Comment by DACOOX360X** [comment]
> @DACOOX360X
> Just realised my wording: I meant if you have it- disable it. It's for certain wi-fi smart devices

No worries, thanks all the same👍
I really like this plugin but would love it to have more user adjustable features like configurable polling rates and more user friend error logs. Is the dev still supporting this as I don’t see many replies to user issues? Maybe his has been busy 😊 @stringbean

**Comment by LewisSpring** [comment]
> > @DACOOX360X
> > Just realised my wording: I meant if you have it- disable it. It's for certain wi-fi smart devices
> 
> No worries, thanks all the same👍
> I really like this plugin but would love it to have more user adjustable features like configurable polling rates and more user friend error logs. Is the dev still supporting this as I don’t see many replies to user issues? Maybe his has been busy 😊 @stringbean

I do wonder and understand if so. I did send a tweet to stringbean, _which i'd not normally do_, but have had no reply.

**Comment by LewisSpring** [comment]
I'd like to note i've manually added the hostname/lan name and the issue still happens

**Comment by DACOOX360X** [comment]
Interestingly, line 80 of the source code file WiserPlatformPlugin.ts seems to print “'Error during system update” and the cached error to the terminal log if the System Polling Update reports a catch error. So the reason it only happens every now and then or erratically may be due to the system no responding to an update request. Might be something silly like the Wiser Hub dropping out on the WiFi or something.
Again I’m probably barking up the wrong tree and it’s just speculation. Would love to know what @stringbean thoughts are....

**Comment by LewisSpring** [comment]
> Interestingly, line 80 of the source code file WiserPlatformPlugin.ts seems to print “'Error during system update” and the cached error to the terminal log if the System Polling Update reports a catch error. So the reason it only happens every now and then or erratically may be due to the system no responding to an update request. Might be something silly like the Wiser Hub dropping out on the WiFi or something.
> Again I’m probably barking up the wrong tree and it’s just speculation. Would love to know what @stringbean thoughts are....

As far as I know, I've only had one real outage of Drayton Wiser a few weeks back. It was overnight, and I'm not too sure why.
I did have a network outage today, where I had to reboot WiFi/Internet - but this system-not-found issue has occoured when the network has been stable (at least as far as I could tell)

**Comment by LewisSpring** [comment]
Even about 10 minutes ago - I was getting system not found errors.

I'm sure it must be a API issue. My HubR is close to the router and i've been using the internet/network fine as far as i can tell.

**Comment by MingChops** [comment]
No I don't have the Tuya plugin. I only have Hue, Wiser and Xbox.

To be fair the Wiser plugin works flawlessly, never had a single issue in terms of operating it from HomeKit app. Other than the annoying red text on Homebridge home screen you would not know anything was wrong.

My router is ****, NetGear R8000. I hate it, and will be replacing very soon once I've decided what to go with. Perhaps an AP mesh setup and I'll stick an AP very close to the Wider hub... when I change will update.

**Comment by DACOOX360X** [comment]
It’s certainly a strange one...

I know when the error happens as I notice my Home app reports incorrect heat set point values. 
Probably because it can’t update and uses existing stale data.

When I check the Homebridge Accessory View the setpoint temp values are wrong there too. This should point to the issue being somewhere between the Wiser HUBR and Homebridge, and not between Homebridge and HomeKit.

Then I check the Homebridge Log and the ‘system not found‘ errors are there in red.

**Comment by LewisSpring** [comment]
I'm glad you're having similar issues - though normal operation seems to have improved for me since removing tuya-web - I'm using HOOBS. I know Homebridge and HOOBs are practically the same, there are differences.

**Comment by ChristopherJohnKelly** [comment]
I am having exactly the same issue. It seemed to go away temporarily when I updated my config to include the (existing) static IP for the Wiser hub, but back today with the same errors as you.

**Comment by timbojoeNBD** [comment]
Me too - any idea how I can help to support any fix for this? I want to help - but don't know how. Thank you!

**Comment by andyblac** [comment]
just bought a starter kit, (waiting for it to arrive), s this plugin still working for broken ?

**Comment by andyblac** [comment]
> I have an issue with the plugin showing the following information on the Homebridge status page log:
> 
> [12/5/2020, 5:07:32 PM] [drayton-wiser] Error during system update Error: system-not-found at WiserClient.request (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:337:15) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:93:5) at WiserClient.fullStatus (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:68:22) at WiserPlatformPlugin.updateSystem (/usr/local/lib/node_modules/@string-bean/homebridge-drayton-wiser/src/WiserPlatformPlugin.ts:101:26)
> 
> I have no idea why or what it means? It is quite random in it's appearance in the log. The plugin otherwise seems to work fine.

just had a quick look at the code, next time it happens try to open a webpage `http://xxx.xxx.xxx.xxx/data/domain/` (use your drayton hubr ip address, it just seems like it failed to respond to the data request.

once I get mine, if i get any errors I will try to debug, I mainly know python and not java, but i'll give it a go.

**Comment by mar894q** [comment]
Any update on this? Issue is still valid after 4 years.

**Comment by MingChops** [comment]
It was still an issue the last time I used it, but I switched to the HomeAssistant integration for Wiser (plus HomeKit bridge to expose the Wiser devices). It is a little more effort to setup as you would expect with HA, but it’s considerably faster and more responsive in terms of heating control, and you can also expose heating and hot water boost modes which I find very useful. Worth switching IMO.

**Comment by mar894q** [comment]
Thanks, I’ll have a look at HA!

**Comment by DACOOX360X** [comment]
@mar894q @MingChops I am also still having the same issues too after 4 years. Found it too unstable, very slow and I really don’t like how it doesn’t manage HomeKit state correctly as it’s very tough to work out if it’s Heating, at the Set Point or OFF. 
This plugin is so bad that I only really use it to get temperature read-outs for each of my rooms, and for actual control of the system I reverted back to using the Wiser App to control my system again. This is not what I want, as like you guys, I want all my automation brought into the HomeKit environment, not separate third-party apps.
Thanks @MingChops for recommending  HomeAssistant, this is deffo the way forward and I will get it set up when I get chance. Will report back when I’ve had a go.
Really disappointed in @stringbean for not bothering to reply to anyone’s messages, not sure why some people join a community lead platform like GitHub when they act like that.

**Comment by DACOOX360X** [comment]
@stringbean 

Everyone has their own things going on in life and we appreciate that you may not be supporting this project any more, but at least have the decency to send a short message explaining that, and not simply choosing to ghost everyone. Not cool.

**Comment by mar894q** [comment]
> [@mar894q](https://github.com/mar894q) [@MingChops](https://github.com/MingChops) I am also still having the same issues too after 4 years. Found it too unstable, very slow and I really don’t like how it doesn’t manage HomeKit state correctly as it’s very tough to work out if it’s Heating, at the Set Point or OFF. This plugin is so bad that I only really use it to get temperature read-outs for each of my rooms, and for actual control of the system I reverted back to using the Wiser App to control my system again. This is not what I want, as like you guys, I want all my automation brought into the HomeKit environment, not separate third-party apps. Thanks [@MingChops](https://github.com/MingChops) for recommending HomeAssistant, this is deffo the way forward and I will get it set up when I get chance. Will report back when I’ve had a go. Really disappointed in [@stringbean](https://github.com/stringbean) for not bothering to reply to anyone’s messages, not sure why some people join a community lead platform like GitHub when they act like that.

I will go the same way and switch to HA as the heating system is one of my key home automation components. It’s a pitty that the Homebridge community apparently is not vivid enough (anymore). 
Let’s share our experiences with the switch to HA for wiser here.

**Comment by mar894q** [comment]
In case you haven’t seen: the new wiser app includes matter API, so you can get your wiser devices (heater but also others like blinds straight into home app. I deactivated stringbean’s plugin.

**Comment by DACOOX360X** [comment]
My HUB R still doesn’t seem to support Matter yet, it’s not an option in the Account > App and Connections > Matter page.

I followed this guide (https://www.productinfo.schneider-electric.com/wiser_home/wiser-home-sug-france/English/SUG%20Wiser%20Home%20F%20(bookmap)_0000804358.xml/$/MatterCommissioning_WHCPT_DD00985414)

I expected to see Matter listed as one of the “Third Party Connections” but no dice. I’ve attached a screenshot from my iPhone.
Did you have to update your HUB R or do it a different way?
Is yours all working now through Matter then?

![Image](https://github.com/user-attachments/assets/d54fdc92-9f01-4095-86f7-138586ce27f4)
![Image](https://github.com/user-attachments/assets/0b21237b-a469-4d2a-aa3c-ad6b05563079)

**Comment by DACOOX360X** [comment]
My HUBR is Firmware Version 3.18.3, not sure what yours is?

Thanks for letting us know about Matter API, I wasn’t aware.

**Comment by DACOOX360X** [comment]
I suspect you need a “2nd Gen HUB R”, I have a 1st Gen. All the Matter documentation references 2nd Gen, but doesn’t specifically say not compatible with 1st Gen. I will call Drayton Wiser Tech Support tomorrow to confirm, and if anything is in the pipeline for 1st Gen customers. I’d assume not as it’s a good way of forcing you to upgrade.

**Comment by mar894q** [comment]
I have a 2nd Gen Hub (firmware 4.38.48) and since the app update a few days ago I can select matter as a third party service:

![Image](https://github.com/user-attachments/assets/5214744d-877c-4559-8f81-87c0ed7c75bf)

**Comment by garvanky** [comment]
@mar894q Curious if you have been able to connect your Wiser Hub Gen 2 via Matter to HomeKit? How has it been? I'm considering upgrading my Gen 1 Hub to Gen 2 just to make the HomeKit integration more seamless (and retire the  Drayton-wiser plug-in). But I would first like to confirm it does actually work correctly! Thanks in advance.
