### ISSUE TITLE
Unexpected-Response error

### ISSUE THREAD

**Issue by LewisSpring** [stringbean/homebridge-drayton-wiser#8]
`[drayton-wiser] Error during system update Error: unexpected-response
    at WiserClient.fullStatus (/home/hoobs/.hoobs/node_modules/@string-bean/drayton-wiser-client/dist/WiserClient.js:62:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WiserPlatformPlugin.updateSystem (/home/hoobs/.hoobs/node_modules/@string-bean/homebridge-drayton-wiser/dist/WiserPlatformPlugin.js:61:30)`

HOOBS 3.3.2.
Let me know if I can provide any more information

**Comment by RustyTravelBoy** [comment]
Same issue here. For a while now this error appears. 
First I thought that the secret key might have changed after software update on the Wiser, but that wasn't the case. 
I then added the Wiser's IP address to the config to make sure it's not related to WiFi coverage.


`[1/26/2021, 2:15:11 PM] [drayton-wiser] Error during system update Error: unexpected-error
    at WiserClient.request (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:340:13)
    at WiserClient.fullStatus (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:68:22)
    at WiserPlatformPlugin.updateSystem (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/src/WiserPlatformPlugin.ts:101:26)`

`[1/26/2021, 5:37:11 PM] [drayton-wiser] Error during system update Error: unexpected-error
    at WiserClient.request (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:340:13)
    at WiserClient.fullStatus (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:68:22)
    at WiserPlatformPlugin.updateSystem (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/src/WiserPlatformPlugin.ts:101:26)`

`[1/26/2021, 7:16:11 PM] [drayton-wiser] Error during system update Error: unexpected-error
    at WiserClient.request (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:340:13)
    at WiserClient.fullStatus (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:68:22)
    at WiserPlatformPlugin.updateSystem (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/src/WiserPlatformPlugin.ts:101:26)`

`[1/26/2021, 7:43:11 PM] [drayton-wiser] Error during system update Error: unexpected-error
    at WiserClient.request (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:340:13)
    at WiserClient.fullStatus (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/node_modules/@string-bean/drayton-wiser-client/src/WiserClient.ts:68:22)
    at WiserPlatformPlugin.updateSystem (/usr/lib/node_modules/@string-bean/homebridge-drayton-wiser/src/WiserPlatformPlugin.ts:101:26)`

**Comment by LewisSpring** [comment]
Not sure on the state of this issue - The project seems abandoned and I no longer use this plugin, nor Homebridge.
Closing for no progress.
